### ISSUE TITLE
Version 1.0.1 not published on Homebrew

### ISSUE THREAD

**Issue by pbernery** [NSHipster/uti#1]
Hello,

I've just tried to install uti through Homebrew and got the version 1.0.0, while the latest version is 1.0.1.
I cloned the repo at the end, but having the updated version on Homebrew could help.

**Comment by mattt** [comment]
Thanks for pointing this out, @pbernery. Apologies for the inconvenience. I just fixed this with https://github.com/NSHipster/homebrew-formulae/commit/7df9c82de1d617c4403a3b46335201cd7409c0b8.

**Comment by pbernery** [comment]
No worries ;-)
